### ISSUE TITLE
Font awesome 5 support

### ISSUE THREAD

**Issue by charlesvdv** [jystic/elm-font-awesome#9]
Hey!

I was thinkering this afternoon about creating an elm package containing every [font awesome 5 icons](https://fontawesome.com/?utm_source=font_awesome_homepage&utm_medium=display&utm_campaign=fa5_released&utm_content=banner) before I found your project.

The new release already contains all icons in svg format in `advanced-options/raw-svg/`. 

Will you be interested into switching to the new version of font awesome ? Of course, I can contribute it myself but I prefer to check with you if that's ok.

**Comment by alicebob** [comment]
This looks great!
